"""
Knowledge Base Expansion - Additional 30 FAQs to reach 50+ total
================================================================
Adds comprehensive FAQs covering all aspects of YYD tours
"""

ADDITIONAL_FAQS = [
    # CANCELLATION & MODIFICATIONS
    {
        "category": "policies",
        "tags": ["cancellation", "refund", "modification", "policy"],
        "confidence": 1.0,
        "en": "Cancellation Policy: Free cancellation up to 24 hours before your tour start time for a full refund. Cancellations within 24 hours are non-refundable. To cancel or modify your booking, contact us via WhatsApp +351 917 756 732 or email info@yesyoudeserve.tours as soon as possible. We understand plans change - if you need to reschedule, we'll do our best to find an alternative date that works for you at no extra charge (subject to availability). No-shows are non-refundable.",
        "pt": "Política de Cancelamento: Cancelamento grátis até 24 horas antes do horário de início do tour para reembolso total. Cancelamentos dentro de 24 horas não são reembolsáveis. Para cancelar ou modificar sua reserva, entre em contato via WhatsApp +351 917 756 732 ou email info@yesyoudeserve.tours o mais rápido possível. Entendemos que planos mudam - se precisar reagendar, faremos o melhor para encontrar uma data alternativa que funcione para você sem custo extra (sujeito a disponibilidade). No-shows não são reembolsáveis.",
        "es": "Política de Cancelación: Cancelación gratuita hasta 24 horas antes de la hora de inicio del tour para reembolso completo. Cancelaciones dentro de 24 horas no son reembolsables. Para cancelar o modificar su reserva, contáctenos vía WhatsApp +351 917 756 732 o email info@yesyoudeserve.tours lo antes posible. Entendemos que los planes cambian - si necesita reprogramar, haremos lo mejor para encontrar una fecha alternativa que funcione para usted sin cargo extra (sujeto a disponibilidad). No-shows no son reembolsables."
    },
    
    # ACCESSIBILITY
    {
        "category": "accessibility",
        "tags": ["wheelchair", "mobility", "elderly", "disabilities", "accessible"],
        "confidence": 1.0,
        "en": "Accessibility: Our electric tuk-tuks are accessible for most guests with moderate mobility. However, they are NOT wheelchair accessible and require climbing 2-3 steps to enter. We welcome elderly guests and those with mild mobility limitations - our guides will assist and we can adjust the pace. Monument interiors often have stairs and uneven surfaces. If you have specific accessibility needs, please inform us when booking so we can customize your experience. We can focus on viewpoints and outside visits rather than climbing to monument interiors. Service animals are welcome.",
        "pt": "Acessibilidade: Nossos tuk-tuks elétricos são acessíveis para a maioria dos hóspedes com mobilidade moderada. No entanto, NÃO são acessíveis para cadeiras de rodas e requerem subir 2-3 degraus para entrar. Recebemos hóspedes idosos e aqueles com limitações leves de mobilidade - nossos guias ajudarão e podemos ajustar o ritmo. Interiores de monumentos frequentemente têm escadas e superfícies irregulares. Se você tem necessidades específicas de acessibilidade, por favor nos informe ao reservar para que possamos personalizar sua experiência. Podemos focar em mirantes e visitas externas em vez de subir para interiores de monumentos. Animais de serviço são bem-vindos.",
        "es": "Accesibilidad: Nuestros tuk-tuks eléctricos son accesibles para la mayoría de huéspedes con movilidad moderada. Sin embargo, NO son accesibles para sillas de ruedas y requieren subir 2-3 escalones para entrar. Recibimos huéspedes mayores y aquellos con limitaciones leves de movilidad - nuestros guías ayudarán y podemos ajustar el ritmo. Los interiores de monumentos frecuentemente tienen escaleras y superficies irregulares. Si tiene necesidades específicas de accesibilidad, por favor infórmenos al reservar para que podamos personalizar su experiencia. Podemos enfocarnos en miradores y visitas externas en lugar de subir a interiores de monumentos. Animales de servicio son bienvenidos."
    },
    
    # WEATHER & CLOTHING
    {
        "category": "practical",
        "tags": ["weather", "rain", "clothing", "what to wear", "temperature"],
        "confidence": 1.0,
        "en": "Weather & Clothing: Sintra has a unique microclimate - it's typically 5-10°C cooler than Lisbon and can be foggy or rainy even when Lisbon is sunny. Layer your clothing! Bring a light jacket even in summer. Our tuk-tuks have rain covers and blankets for chilly weather. Tours run rain or shine - we've never cancelled due to weather! If it rains, we adapt the route to covered viewpoints and indoor monument visits. Comfortable walking shoes are essential (no heels!). Sunscreen and hat recommended for sunny days. Sintra can be windy, especially at Cabo da Roca.",
        "pt": "Clima & Vestuário: Sintra tem um microclima único - é tipicamente 5-10°C mais fria que Lisboa e pode estar nebulosa ou chuvosa mesmo quando Lisboa está ensolarada. Vista-se em camadas! Traga uma jaqueta leve mesmo no verão. Nossos tuk-tuks têm coberturas de chuva e cobertores para clima frio. Tours acontecem com chuva ou sol - nunca cancelamos devido ao clima! Se chover, adaptamos a rota para mirantes cobertos e visitas internas a monumentos. Sapatos confortáveis para caminhar são essenciais (nada de saltos!). Protetor solar e chapéu recomendados para dias ensolarados. Sintra pode ser ventosa, especialmente no Cabo da Roca.",
        "es": "Clima y Vestuario: Sintra tiene un microclima único - es típicamente 5-10°C más fría que Lisboa y puede estar neblinosa o lluviosa incluso cuando Lisboa está soleada. ¡Vístase en capas! Traiga una chaqueta ligera incluso en verano. Nuestros tuk-tuks tienen cubiertas de lluvia y mantas para clima frío. Los tours se realizan con lluvia o sol - ¡nunca cancelamos debido al clima! Si llueve, adaptamos la ruta a miradores cubiertos y visitas internas a monumentos. Zapatos cómodos para caminar son esenciales (¡nada de tacones!). Protector solar y sombrero recomendados para días soleados. Sintra puede ser ventosa, especialmente en Cabo da Roca."
    },
    
    # CHILDREN & FAMILIES
    {
        "category": "family",
        "tags": ["children", "kids", "family", "babies", "age limit"],
        "confidence": 1.0,
        "en": "Children & Families: Families are very welcome! Children of all ages can join our tours. Kids usually love the tuk-tuk ride and exploring castles. No car seats or booster seats required by Portuguese law for tuk-tuks. Our guides are experienced with families and can adjust storytelling for children's attention spans. Bring snacks and water for kids. Monument visits can involve walking - consider a baby carrier rather than stroller (cobblestones and stairs!). Children under 6 typically get free or discounted monument tickets. Our guides have helped countless families create magical memories in Sintra!",
        "pt": "Crianças & Famílias: Famílias são muito bem-vindas! Crianças de todas as idades podem participar de nossos tours. Crianças geralmente adoram o passeio de tuk-tuk e explorar castelos. Não são necessários assentos de carro ou assentos elevatórios pela lei portuguesa para tuk-tuks. Nossos guias são experientes com famílias e podem ajustar a narrativa para a capacidade de atenção das crianças. Traga lanches e água para crianças. Visitas a monumentos podem envolver caminhada - considere um porta-bebê em vez de carrinho (paralelepípedos e escadas!). Crianças menores de 6 anos tipicamente ganham ingressos de monumentos grátis ou com desconto. Nossos guias ajudaram inúmeras famílias a criar memórias mágicas em Sintra!",
        "es": "Niños y Familias: ¡Las familias son muy bienvenidas! Niños de todas las edades pueden unirse a nuestros tours. A los niños generalmente les encanta el paseo en tuk-tuk y explorar castillos. No se requieren asientos de auto o asientos elevadores por ley portuguesa para tuk-tuks. Nuestros guías son experimentados con familias y pueden ajustar la narración para la capacidad de atención de los niños. Traiga bocadillos y agua para niños. Las visitas a monumentos pueden involucrar caminata - considere un portabebés en lugar de cochecito (¡adoquines y escaleras!). Niños menores de 6 años típicamente obtienen entradas de monumentos gratis o con descuento. ¡Nuestros guías han ayudado a innumerables familias a crear recuerdos mágicos en Sintra!"
    },
    
    # PHOTOGRAPHY
    {
        "category": "photography",
        "tags": ["photos", "camera", "instagram", "pictures", "drone"],
        "confidence": 1.0,
        "en": "Photography: Professional photography is INCLUDED in all our tours! Your guide knows the best angles, lighting, and Instagram spots. They'll take unlimited photos of you with your phone or camera throughout the day - no need for selfie sticks! Best photo times: early morning (9-11am) for soft light and fewer crowds. Pena Palace photos are spectacular from multiple viewpoints. Bring your phone/camera fully charged. Drones are prohibited at all monuments and most Sintra parks without special permits. You're welcome to bring professional camera equipment. Your guide will capture candid moments and ensure you leave with frame-worthy memories!",
        "pt": "Fotografia: Fotografia profissional está INCLUÍDA em todos os nossos tours! Seu guia conhece os melhores ângulos, iluminação e locais Instagram. Eles tirarão fotos ilimitadas de você com seu telefone ou câmera durante todo o dia - não precisa de pau de selfie! Melhores horários para fotos: manhã cedo (9-11h) para luz suave e menos multidões. Fotos do Palácio da Pena são espetaculares de múltiplos mirantes. Traga seu telefone/câmera totalmente carregado. Drones são proibidos em todos os monumentos e a maioria dos parques de Sintra sem autorizações especiais. Você pode trazer equipamento de câmera profissional. Seu guia capturará momentos espontâneos e garantirá que você saia com memórias dignas de moldura!",
        "es": "Fotografía: ¡Fotografía profesional está INCLUIDA en todos nuestros tours! Su guía conoce los mejores ángulos, iluminación y lugares Instagram. Tomarán fotos ilimitadas de usted con su teléfono o cámara durante todo el día - ¡no necesita palo de selfie! Mejores horarios para fotos: temprano en la mañana (9-11am) para luz suave y menos multitudes. Fotos del Palacio de Pena son espectaculares desde múltiples miradores. Traiga su teléfono/cámara completamente cargado. Drones están prohibidos en todos los monumentos y la mayoría de los parques de Sintra sin permisos especiales. Puede traer equipo de cámara profesional. ¡Su guía capturará momentos espontáneos y asegurará que salga con recuerdos dignos de enmarcar!"
    },
    
    # PAYMENT METHODS
    {
        "category": "payment",
        "tags": ["payment", "credit card", "cash", "money", "currency"],
        "confidence": 1.0,
        "en": "Payment Methods: We accept multiple payment options for your convenience: Cash (Euros), Credit/Debit Cards (Visa, Mastercard, American Express), Bank Transfer, PayPal, and MBWay (Portuguese mobile payment). Payment is typically made on the day of the tour, though we can arrange advance payment if preferred. For All-Inclusive tours, we handle all payments including monuments, lunch, and wine tasting - you don't need to carry cash. Monument tickets can be paid separately in cash or card. Tipping is appreciated but never expected. ATMs are available in Sintra town center.",
        "pt": "Métodos de Pagamento: Aceitamos múltiplas opções de pagamento para sua conveniência: Dinheiro (Euros), Cartões de Crédito/Débito (Visa, Mastercard, American Express), Transferência Bancária, PayPal e MBWay (pagamento móvel português). O pagamento é tipicamente feito no dia do tour, embora possamos arranjar pagamento antecipado se preferido. Para tours All-Inclusive, nós cuidamos de todos os pagamentos incluindo monumentos, almoço e degustação de vinhos - você não precisa carregar dinheiro. Ingressos de monumentos podem ser pagos separadamente em dinheiro ou cartão. Gorjetas são apreciadas mas nunca esperadas. Caixas eletrônicos estão disponíveis no centro da vila de Sintra.",
        "es": "Métodos de Pago: Aceptamos múltiples opciones de pago para su conveniencia: Efectivo (Euros), Tarjetas de Crédito/Débito (Visa, Mastercard, American Express), Transferencia Bancaria, PayPal y MBWay (pago móvil portugués). El pago es típicamente realizado el día del tour, aunque podemos organizar pago anticipado si se prefiere. Para tours All-Inclusive, nos encargamos de todos los pagos incluyendo monumentos, almuerzo y cata de vinos - no necesita llevar efectivo. Entradas de monumentos pueden pagarse por separado en efectivo o tarjeta. Las propinas son apreciadas pero nunca esperadas. Cajeros automáticos están disponibles en el centro del pueblo de Sintra."
    },
    
    # GROUP SIZE & PRIVATE EVENTS
    {
        "category": "groups",
        "tags": ["group", "corporate", "private event", "wedding", "party"],
        "confidence": 1.0,
        "en": "Group Size & Private Events: Our tuk-tuks accommodate up to 6 people comfortably. For larger groups (7-36+ people), we coordinate multiple tuk-tuks traveling together with walkie-talkies for communication. Perfect for corporate events, team building, family reunions, bachelor/bachelorette parties, and wedding groups! We offer special group rates and can customize experiences. All our tours are 100% private - you'll never be grouped with strangers. For corporate events, we can provide invoices, customize routes for team activities, and arrange special lunch venues. Contact us for groups of 10+ for custom pricing and planning.",
        "pt": "Tamanho do Grupo & Eventos Privados: Nossos tuk-tuks acomodam até 6 pessoas confortavelmente. Para grupos maiores (7-36+ pessoas), coordenamos múltiplos tuk-tuks viajando juntos com walkie-talkies para comunicação. Perfeito para eventos corporativos, team building, reuniões familiares, despedidas de solteiro/solteira e grupos de casamento! Oferecemos tarifas especiais para grupos e podemos personalizar experiências. Todos os nossos tours são 100% privados - você nunca será agrupado com estranhos. Para eventos corporativos, podemos fornecer faturas, personalizar rotas para atividades de equipe e arranjar locais especiais para almoço. Entre em contato para grupos de 10+ para preços e planejamento customizados.",
        "es": "Tamaño de Grupo y Eventos Privados: Nuestros tuk-tuks acomodan hasta 6 personas cómodamente. Para grupos más grandes (7-36+ personas), coordinamos múltiples tuk-tuks viajando juntos con walkie-talkies para comunicación. ¡Perfecto para eventos corporativos, team building, reuniones familiares, despedidas de soltero/soltera y grupos de boda! Ofrecemos tarifas especiales para grupos y podemos personalizar experiencias. Todos nuestros tours son 100% privados - nunca será agrupado con extraños. Para eventos corporativos, podemos proporcionar facturas, personalizar rutas para actividades de equipo y organizar lugares especiales para almuerzo. Contáctenos para grupos de 10+ para precios y planificación personalizados."
    },
    
    # LANGUAGES
    {
        "category": "languages",
        "tags": ["language", "english", "spanish", "portuguese", "translation"],
        "confidence": 1.0,
        "en": "Languages: All our guides are fluent in English and Portuguese. Many also speak Spanish! When booking, let us know your preferred language and we'll match you with the perfect guide. Our founder Daniel Ponce speaks Portuguese, English, and Spanish fluently. The tour experience is the same quality in all languages - local insights, stories, and historical context adapted to your language. Monument signage is typically in Portuguese and English. Audio guides at monuments are available in 10+ languages if you want additional detail during interior visits.",
        "pt": "Idiomas: Todos os nossos guias são fluentes em Inglês e Português. Muitos também falam Espanhol! Ao reservar, nos informe seu idioma preferido e combinaremos você com o guia perfeito. Nosso fundador Daniel Ponce fala Português, Inglês e Espanhol fluentemente. A experiência do tour é da mesma qualidade em todos os idiomas - insights locais, histórias e contexto histórico adaptado ao seu idioma. Sinalização de monumentos é tipicamente em Português e Inglês. Audioguias em monumentos estão disponíveis em mais de 10 idiomas se você quiser detalhes adicionais durante visitas internas.",
        "es": "Idiomas: Todos nuestros guías son fluidos en Inglés y Portugués. ¡Muchos también hablan Español! Al reservar, infórmenos su idioma preferido y lo emparejaremos con el guía perfecto. Nuestro fundador Daniel Ponce habla Portugués, Inglés y Español con fluidez. La experiencia del tour es de la misma calidad en todos los idiomas - perspectivas locales, historias y contexto histórico adaptado a su idioma. La señalización de monumentos es típicamente en Portugués e Inglés. Audioguías en monumentos están disponibles en más de 10 idiomas si quiere detalles adicionales durante visitas interiores."
    },
    
    # DIETARY RESTRICTIONS
    {
        "category": "food",
        "tags": ["vegetarian", "vegan", "allergies", "dietary", "gluten-free"],
        "confidence": 1.0,
        "en": "Dietary Restrictions: We accommodate all dietary needs! When booking a full-day tour with lunch, please inform us of any dietary restrictions: vegetarian, vegan, gluten-free, dairy-free, nut allergies, religious dietary laws (halal, kosher), etc. Portuguese restaurants are usually very accommodating. Traditional vegetarian options include vegetable rice, grilled vegetables, salads, soups, and fresh fish (if pescatarian). Vegan options may be more limited but available. We'll communicate your needs to the restaurant in advance. If you have severe allergies, we recommend bringing emergency medication just in case.",
        "pt": "Restrições Alimentares: Acomodamos todas as necessidades alimentares! Ao reservar um tour de dia completo com almoço, por favor nos informe de quaisquer restrições alimentares: vegetariano, vegano, sem glúten, sem laticínios, alergias a nozes, leis alimentares religiosas (halal, kosher), etc. Restaurantes portugueses geralmente são muito acomodatícios. Opções vegetarianas tradicionais incluem arroz de legumes, legumes grelhados, saladas, sopas e peixe fresco (se pescetariano). Opções veganas podem ser mais limitadas mas disponíveis. Comunicaremos suas necessidades ao restaurante com antecedência. Se você tem alergias graves, recomendamos trazer medicação de emergência por precaução.",
        "es": "Restricciones Alimentarias: ¡Acomodamos todas las necesidades alimentarias! Al reservar un tour de día completo con almuerzo, por favor infórmenos de cualquier restricción alimentaria: vegetariano, vegano, sin gluten, sin lácteos, alergias a nueces, leyes alimentarias religiosas (halal, kosher), etc. Restaurantes portugueses generalmente son muy acomodaticios. Opciones vegetarianas tradicionales incluyen arroz de vegetales, vegetales a la parrilla, ensaladas, sopas y pescado fresco (si pescetariano). Opciones veganas pueden ser más limitadas pero disponibles. Comunicaremos sus necesidades al restaurante con anticipación. Si tiene alergias graves, recomendamos traer medicación de emergencia por precaución."
    },
    
    # TIPPING
    {
        "category": "tipping",
        "tags": ["tip", "gratuity", "gratitude", "extra payment"],
        "confidence": 1.0,
        "en": "Tipping: Tipping is appreciated but never expected or required! If you enjoyed your tour and want to show appreciation, 10-20% of the tour price is generous but any amount is welcome. Many happy guests tip €20-50 for exceptional service. You can tip in cash (Euros) at the end of the tour directly to your guide. Tips are shared among the team. What matters most to us is your genuine satisfaction and positive reviews - those help our small business grow! If you had a great experience, leaving a review on TripAdvisor, Google, or Facebook means the world to us.",
        "pt": "Gorjetas: Gorjetas são apreciadas mas nunca esperadas ou exigidas! Se você gostou do seu tour e quer mostrar apreciação, 10-20% do preço do tour é generoso mas qualquer quantia é bem-vinda. Muitos hóspedes satisfeitos dão gorjeta de €20-50 por serviço excepcional. Você pode dar gorjeta em dinheiro (Euros) no final do tour diretamente ao seu guia. Gorjetas são compartilhadas entre a equipe. O que mais importa para nós é sua satisfação genuína e avaliações positivas - essas ajudam nosso pequeno negócio a crescer! Se você teve uma ótima experiência, deixar uma avaliação no TripAdvisor, Google ou Facebook significa o mundo para nós.",
        "es": "Propinas: ¡Las propinas son apreciadas pero nunca esperadas o requeridas! Si disfrutó su tour y quiere mostrar apreciación, 10-20% del precio del tour es generoso pero cualquier cantidad es bienvenida. Muchos huéspedes satisfechos dan propina de €20-50 por servicio excepcional. Puede dar propina en efectivo (Euros) al final del tour directamente a su guía. Las propinas son compartidas entre el equipo. Lo que más nos importa es su satisfacción genuina y reseñas positivas - ¡esas ayudan a nuestro pequeño negocio a crecer! Si tuvo una gran experiencia, dejar una reseña en TripAdvisor, Google o Facebook significa el mundo para nosotros."
    },
    
    # SAFETY & INSURANCE
    {
        "category": "safety",
        "tags": ["safety", "insurance", "emergency", "accident", "medical"],
        "confidence": 1.0,
        "en": "Safety & Insurance: Your safety is our top priority! All our tuk-tuks are professionally maintained and regularly inspected. Our guides are trained in first aid and carry emergency contact information. We have comprehensive liability insurance covering all tours. In case of emergency, Portugal's emergency number is 112 (ambulance, police, fire). Hospitals in Sintra and Cascais provide excellent care. We recommend travelers have their own travel insurance covering medical emergencies, trip cancellations, and personal belongings. Our tuk-tuks have seat belts. We drive carefully and follow all traffic laws. COVID-19 protocols: tuk-tuks are sanitized between tours.",
        "pt": "Segurança & Seguro: Sua segurança é nossa prioridade máxima! Todos os nossos tuk-tuks são profissionalmente mantidos e regularmente inspecionados. Nossos guias são treinados em primeiros socorros e carregam informações de contato de emergência. Temos seguro de responsabilidade civil abrangente cobrindo todos os tours. Em caso de emergência, o número de emergência de Portugal é 112 (ambulância, polícia, bombeiros). Hospitais em Sintra e Cascais fornecem cuidados excelentes. Recomendamos que viajantes tenham seu próprio seguro de viagem cobrindo emergências médicas, cancelamentos de viagem e pertences pessoais. Nossos tuk-tuks têm cintos de segurança. Dirigimos com cuidado e seguimos todas as leis de trânsito. Protocolos COVID-19: tuk-tuks são sanitizados entre tours.",
        "es": "Seguridad y Seguro: ¡Su seguridad es nuestra máxima prioridad! Todos nuestros tuk-tuks son mantenidos profesionalmente e inspeccionados regularmente. Nuestros guías están capacitados en primeros auxilios y llevan información de contacto de emergencia. Tenemos seguro de responsabilidad civil integral cubriendo todos los tours. En caso de emergencia, el número de emergencia de Portugal es 112 (ambulancia, policía, bomberos). Hospitales en Sintra y Cascais proporcionan cuidado excelente. Recomendamos que viajeros tengan su propio seguro de viaje cubriendo emergencias médicas, cancelaciones de viaje y pertenencias personales. Nuestros tuk-tuks tienen cinturones de seguridad. Conducimos con cuidado y seguimos todas las leyes de tránsito. Protocolos COVID-19: tuk-tuks son sanitizados entre tours."
    },
    
    # PARKING & FACILITIES
    {
        "category": "logistics",
        "tags": ["parking", "restroom", "bathroom", "facilities", "toilet"],
        "confidence": 1.0,
        "en": "Parking & Facilities: If driving to Sintra, DON'T park at monuments - it's very difficult and expensive! Park in Sintra town center (pay parking) or better yet, take the train from Lisbon. Our meeting point at Sintra train station is easy to reach. During the tour, restroom breaks are available at cafes, restaurants, and monument facilities. Sintra historic center has public restrooms. Monuments have modern, clean facilities. We plan strategic stops for bathroom breaks - just let your guide know if you need one! Cafes are happy to let you use facilities if you buy a coffee. Baby changing facilities available at most monuments.",
        "pt": "Estacionamento & Instalações: Se dirigir para Sintra, NÃO estacione nos monumentos - é muito difícil e caro! Estacione no centro da vila de Sintra (estacionamento pago) ou melhor ainda, pegue o trem de Lisboa. Nosso ponto de encontro na estação de trem de Sintra é fácil de alcançar. Durante o tour, pausas para banheiro estão disponíveis em cafés, restaurantes e instalações de monumentos. O centro histórico de Sintra tem banheiros públicos. Monumentos têm instalações modernas e limpas. Planejamos paradas estratégicas para pausas de banheiro - apenas avise seu guia se precisar! Cafés ficam felizes em deixar você usar as instalações se comprar um café. Instalações para troca de fraldas disponíveis na maioria dos monumentos.",
        "es": "Estacionamiento e Instalaciones: Si conduce a Sintra, ¡NO estacione en monumentos - es muy difícil y caro! Estacione en el centro del pueblo de Sintra (estacionamiento de pago) o mejor aún, tome el tren desde Lisboa. Nuestro punto de encuentro en la estación de tren de Sintra es fácil de alcanzar. Durante el tour, pausas para baño están disponibles en cafés, restaurantes e instalaciones de monumentos. El centro histórico de Sintra tiene baños públicos. Los monumentos tienen instalaciones modernas y limpias. Planeamos paradas estratégicas para pausas de baño - ¡solo avise a su guía si necesita una! Los cafés están felices de dejarle usar las instalaciones si compra un café. Instalaciones para cambio de pañales disponibles en la mayoría de monumentos."
    },
    
    # BEST MONUMENTS TO VISIT
    {
        "category": "recommendations",
        "tags": ["which monuments", "recommendations", "must-see", "top picks"],
        "confidence": 1.0,
        "en": "Which Monuments to Visit: Our top recommendations depend on your interests! MUST-SEE for first-timers: Pena Palace (iconic colorful castle) and Quinta da Regaleira (mystical gardens with Initiation Well). If you have time: Moorish Castle (spectacular views), Sintra National Palace (medieval center, twin chimneys), Monserrate Palace (peaceful, exotic gardens). SKIP if short on time: Chalet Biester, Palácio de Seteais (unless staying there). Outside monuments: Cabo da Roca (westernmost Europe), Azenhas do Mar (cliffside village). We'll help you choose based on your pace, interests (nature vs architecture vs history), and whether you prefer crowded iconic sites or hidden peaceful gems.",
        "pt": "Quais Monumentos Visitar: Nossas principais recomendações dependem dos seus interesses! IMPERDÍVEIS para primeira visita: Palácio da Pena (castelo colorido icônico) e Quinta da Regaleira (jardins místicos com Poço Iniciático). Se tiver tempo: Castelo dos Mouros (vistas espetaculares), Palácio Nacional de Sintra (centro medieval, chaminés gêmeas), Palácio de Monserrate (tranquilo, jardins exóticos). PULE se estiver com pressa: Chalet Biester, Palácio de Seteais (a menos que esteja hospedado lá). Fora monumentos: Cabo da Roca (mais ocidental da Europa), Azenhas do Mar (vila à beira do penhasco). Ajudaremos você a escolher com base no seu ritmo, interesses (natureza vs arquitetura vs história), e se prefere locais icônicos lotados ou joias escondidas tranquilas.",
        "es": "Qué Monumentos Visitar: ¡Nuestras principales recomendaciones dependen de sus intereses! IMPERDIBLES para primera visita: Palacio de Pena (castillo colorido icónico) y Quinta da Regaleira (jardines místicos con Pozo Iniciático). Si tiene tiempo: Castillo de los Moros (vistas espectaculares), Palacio Nacional de Sintra (centro medieval, chimeneas gemelas), Palacio de Monserrate (tranquilo, jardines exóticos). OMITA si tiene prisa: Chalet Biester, Palacio de Seteais (a menos que se hospede allí). Fuera monumentos: Cabo da Roca (más occidental de Europa), Azenhas do Mar (pueblo al borde del acantilado). Le ayudaremos a elegir según su ritmo, intereses (naturaleza vs arquitectura vs historia), y si prefiere sitios icónicos concurridos o joyas escondidas tranquilas."
    },
]

# Total so far: 24 original + 13 new = 37... need 13 more!
